# Gateway Configuration:
server:
  port: ${SERVER_PORT}

spring:
  cloud:
    gateway:
      routes:
        - id: Twits
          uri: ${TWIT_MS_URI}
          predicates:
            - Path=/v1/twit/admin/**
          filters:
            - AuthFilter
            
        - id: Users
          uri: ${USER_MS_URI}
          predicates:
            - Path=/api/v1/admin/**
          filters:
            - AuthFilter
             
           


